"""
Demonstration of the Prover-Estimator Debate Safety Case System
"""
import os
import sys
import json
from typing import Dict, Any

# Add src to path
sys.path.append('./src')

def print_header(title: str):
    """Print a formatted header."""
    print("\n" + "="*60)
    print(f" {title}")
    print("="*60)

def print_section(title: str):
    """Print a formatted section header."""
    print(f"\n📋 {title}")
    print("-" * 40)

def demo_safety_context_generation():
    """Demonstrate safety context generation."""
    print_header("SAFETY CONTEXT GENERATION")
    
    from src.safety_case.generator import SafetyCaseGenerator
    
    # Example system description
    user_input = """
    An AI-powered autonomous vehicle control system that will be deployed in urban 
    environments. The system uses computer vision, lidar, and GPS to navigate roads, 
    avoid obstacles, and follow traffic rules. It will operate in Level 4 autonomy 
    mode with human oversight available but not required for normal operation.
    """
    
    print(f"🚗 System Description: {user_input.strip()}")
    
    # Note: This would normally call the LLM, but we'll use a mock for demo
    print("\n🤖 Generating safety context (mock response)...")
    
    # Mock safety context (what would be generated by LLM)
    mock_context = {
        "system_description": "An AI-powered autonomous vehicle control system for urban environments with Level 4 autonomy, using computer vision, lidar, and GPS for navigation and obstacle avoidance.",
        "deployment_context": "Urban roads with mixed traffic, weather conditions, and pedestrian activity. System operates with human oversight available but not required for normal operation.",
        "safety_claims": [
            "The system can safely navigate urban environments without human intervention",
            "The system correctly identifies and responds to all relevant traffic scenarios",
            "The system maintains safe following distances and speeds in all conditions",
            "The system can safely handle emergency situations and edge cases",
            "The system's decision-making is transparent and auditable"
        ],
        "assumptions": [
            "Sensors (cameras, lidar, GPS) function within specified parameters",
            "Road infrastructure follows standard conventions and signage",
            "Other vehicles and pedestrians behave reasonably predictably",
            "Weather conditions remain within operational parameters",
            "Communication systems for remote oversight remain functional"
        ],
        "risk_factors": [
            "Sensor failure or degradation in adverse weather",
            "Unexpected road conditions or construction zones",
            "Malicious actors attempting to confuse the system",
            "Software bugs or edge cases in decision algorithms",
            "Communication failures preventing human oversight"
        ],
        "mitigation_strategies": [
            "Redundant sensor systems with graceful degradation",
            "Conservative driving behavior in uncertain situations",
            "Real-time monitoring and anomaly detection",
            "Fail-safe mechanisms to safely stop or transfer control",
            "Regular software updates and testing protocols"
        ]
    }
    
    print_section("Generated Safety Context")
    print(f"📝 System: {mock_context['system_description']}")
    print(f"🌍 Context: {mock_context['deployment_context']}")
    print(f"✅ Safety Claims: {len(mock_context['safety_claims'])}")
    print(f"🔍 Assumptions: {len(mock_context['assumptions'])}")
    print(f"⚠️  Risk Factors: {len(mock_context['risk_factors'])}")
    print(f"🛡️  Mitigations: {len(mock_context['mitigation_strategies'])}")
    
    return mock_context

def demo_debate_structure():
    """Demonstrate the debate structure."""
    print_header("PROVER-ESTIMATOR DEBATE STRUCTURE")
    
    print_section("Debate Participants")
    print("🔵 Alice (Prover):")
    print("   • Breaks claims into verifiable subclaims")
    print("   • Selects which subclaim to focus on")
    print("   • Predicts if estimator's probabilities are wrong")
    
    print("\n🔴 Bob (Estimator):")
    print("   • Provides probability estimates for each subclaim")
    print("   • Gives reasoning for probability assessments")
    print("   • Expresses uncertainty about potential flaws")
    
    print("\n🟡 Judge:")
    print("   • Checks consistency between probability estimates")
    print("   • Evaluates if prover correctly predicted errors")
    print("   • Assigns rewards based on protocol rules")
    
    print_section("Example Debate Round")
    
    # Mock debate round
    main_claim = "The autonomous vehicle system can safely navigate urban environments"
    
    print(f"🎯 Main Claim: {main_claim}")
    
    print("\n🔵 Alice breaks this into subclaims:")
    subclaims = [
        "The system accurately detects pedestrians in crosswalks",
        "The system maintains safe following distances from other vehicles", 
        "The system correctly interprets traffic signals and signs",
        "The system can safely merge into traffic lanes"
    ]
    
    for i, subclaim in enumerate(subclaims, 1):
        print(f"   {i}. {subclaim}")
    
    print("\n🔴 Bob provides probability estimates:")
    probabilities = [0.85, 0.92, 0.78, 0.71]
    for i, (subclaim, prob) in enumerate(zip(subclaims, probabilities), 1):
        print(f"   {i}. {prob:.0%} - {subclaim}")
    
    print("\n🔵 Alice selects subclaim 4 (lowest probability)")
    print("   Prediction: Bob UNDERESTIMATED the probability")
    print("   Reasoning: Merging algorithms have been extensively tested")
    
    print("\n🟡 Judge evaluates:")
    print("   • Checks if probabilities are consistent with main claim")
    print("   • Determines if Alice's prediction about underestimation is correct")
    print("   • Assigns rewards: Alice +2.5², Bob -2.5² (if Alice correct)")

def demo_safety_analysis():
    """Demonstrate safety analysis results."""
    print_header("SAFETY ANALYSIS RESULTS")
    
    # Mock analysis results
    mock_analysis = {
        "overall_assessment": "The autonomous vehicle system shows strong safety foundations with well-designed redundancy and fail-safe mechanisms. However, several areas require additional validation, particularly around edge case handling and sensor reliability in adverse conditions.",
        "confidence_score": 0.73,
        "risk_level": "medium",
        "claim_assessments": [
            {
                "claim": "System can safely navigate urban environments",
                "confidence": 0.75,
                "evidence_strength": "moderate",
                "key_concerns": ["Edge case handling", "Sensor degradation"]
            },
            {
                "claim": "System correctly identifies traffic scenarios", 
                "confidence": 0.82,
                "evidence_strength": "strong",
                "key_concerns": ["Novel road configurations"]
            }
        ],
        "vulnerabilities": [
            {
                "vulnerability": "Sensor failure in adverse weather",
                "severity": "high", 
                "likelihood": 0.15,
                "mitigation": "Implement redundant sensor fusion with graceful degradation"
            },
            {
                "vulnerability": "Edge case decision making",
                "severity": "medium",
                "likelihood": 0.25, 
                "mitigation": "Expand training data and testing scenarios"
            }
        ],
        "recommendations": [
            "Conduct extensive testing in adverse weather conditions",
            "Develop more robust edge case handling algorithms",
            "Implement additional sensor redundancy",
            "Create comprehensive monitoring and logging systems"
        ]
    }
    
    print_section("Overall Assessment")
    print(f"📊 Confidence Score: {mock_analysis['confidence_score']:.0%}")
    print(f"⚠️  Risk Level: {mock_analysis['risk_level'].upper()}")
    print(f"📝 Assessment: {mock_analysis['overall_assessment']}")
    
    print_section("Key Vulnerabilities")
    for vuln in mock_analysis['vulnerabilities']:
        severity_emoji = {"high": "🔴", "medium": "🟡", "low": "🟢"}
        print(f"{severity_emoji[vuln['severity']]} {vuln['vulnerability']}")
        print(f"   Likelihood: {vuln['likelihood']:.0%} | Severity: {vuln['severity']}")
        print(f"   Mitigation: {vuln['mitigation']}")
    
    print_section("Recommendations")
    for i, rec in enumerate(mock_analysis['recommendations'], 1):
        print(f"{i}. {rec}")

def demo_probability_estimates():
    """Demonstrate probability estimates."""
    print_header("PROBABILITY ESTIMATES")
    
    # Mock probability estimates
    mock_probabilities = {
        "overall_safety_probability": 0.73,
        "claim_probabilities": {
            "Safe navigation": 0.75,
            "Traffic scenario recognition": 0.82, 
            "Safe following distances": 0.78,
            "Emergency handling": 0.65,
            "Decision transparency": 0.71
        },
        "confidence_intervals": {
            "Safe navigation": [0.65, 0.85],
            "Traffic scenario recognition": [0.75, 0.89],
            "Safe following distances": [0.70, 0.86], 
            "Emergency handling": [0.55, 0.75],
            "Decision transparency": [0.62, 0.80]
        },
        "key_uncertainties": [
            "Limited real-world testing data in edge conditions",
            "Uncertainty about long-term sensor reliability",
            "Variability in human behavior and road conditions"
        ]
    }
    
    print_section("Safety Claim Probabilities")
    for claim, prob in mock_probabilities['claim_probabilities'].items():
        interval = mock_probabilities['confidence_intervals'][claim]
        print(f"📊 {claim}: {prob:.0%} (CI: {interval[0]:.0%}-{interval[1]:.0%})")
    
    print(f"\n🎯 Overall Safety Probability: {mock_probabilities['overall_safety_probability']:.0%}")
    
    print_section("Key Uncertainties")
    for uncertainty in mock_probabilities['key_uncertainties']:
        print(f"❓ {uncertainty}")

def demo_visualization_concepts():
    """Demonstrate visualization concepts."""
    print_header("VISUALIZATION CONCEPTS")
    
    print_section("Available Visualizations")
    
    visualizations = [
        ("🌳 Debate Tree", "Shows hierarchical structure of claim decomposition"),
        ("📈 Reward Progression", "Tracks cumulative rewards through debate rounds"),
        ("🔗 Argument Structure", "Visualizes logical connections between claims"),
        ("📊 Safety Overview", "Comprehensive dashboard with confidence scores"),
        ("🔥 Probability Heatmap", "Compares estimates across multiple debates")
    ]
    
    for viz_name, description in visualizations:
        print(f"{viz_name}: {description}")
    
    print_section("Example Debate Tree Structure")
    print("""
    Main Claim: "System is safe for urban deployment"
    ├── Subclaim 1: "Accurate pedestrian detection" (85%)
    │   ├── "Detects in daylight" (95%)
    │   ├── "Detects in low light" (75%) ← Selected for recursion
    │   └── "Detects with occlusion" (80%)
    ├── Subclaim 2: "Safe following distances" (92%)
    ├── Subclaim 3: "Traffic signal recognition" (78%)
    └── Subclaim 4: "Emergency response" (71%)
    """)

def main():
    """Run the complete demonstration."""
    print("🛡️ PROVER-ESTIMATOR DEBATE SAFETY CASE SYSTEM")
    print("Based on UK AISI Alignment Team Research")
    print("https://www.alignmentforum.org/s/NdovveRcyfxgMoujf")
    
    # Run demonstration sections
    safety_context = demo_safety_context_generation()
    demo_debate_structure()
    demo_safety_analysis()
    demo_probability_estimates()
    demo_visualization_concepts()
    
    print_header("SYSTEM CAPABILITIES SUMMARY")
    
    capabilities = [
        "✅ Implements prover-estimator debate protocol from alignment research",
        "✅ Generates comprehensive safety cases for AI systems", 
        "✅ Provides calibrated probability estimates for safety claims",
        "✅ Creates interactive visualizations of debate structure",
        "✅ Supports multiple LLM providers via OpenRouter",
        "✅ Includes web interface for easy interaction",
        "✅ Built on Inspect AI framework for robust evaluation"
    ]
    
    for capability in capabilities:
        print(capability)
    
    print_header("NEXT STEPS")
    
    print("🚀 To use the system:")
    print("1. Set up API keys in .env file")
    print("2. Run web interface: streamlit run app.py --server.port 12000 --server.address 0.0.0.0")
    print("3. Or use Python API: python example_usage.py")
    print("4. Or run Inspect AI evaluation: from src.inspect_eval import run_safety_case_evaluation")
    
    print("\n📚 For more information:")
    print("• Read FRAMEWORK_CONTEXT.md for theoretical background")
    print("• Check README.md for detailed usage instructions")
    print("• Review the alignment forum papers for research context")
    
    print("\n🎯 Current web interface: https://work-1-yfgjbvjleccopvbt.prod-runtime.all-hands.dev")

if __name__ == "__main__":
    main()